export const ProjectsList = [
  {
    id: 1,
    title: "Philippine Scripts Translator",
    icon: "https://tailwindcss.com/_next/static/media/tailwindcss-mark.3c5441fc7a190fb1800d4a5c7f07ba4b1345a9c8.svg",
    inDevelopment: false,
    hasUrl: true,
    url: "https://v2.translate.jennayey.com",
    linkText: "Visit",
    isDeveloper: true,
    isDesigner: true,
  },
  {
    id: 2,
    title: "Somber",
    icon: "https://tailwindcss.com/_next/static/media/tailwindcss-mark.3c5441fc7a190fb1800d4a5c7f07ba4b1345a9c8.svg",
    inDevelopment: false,
    hasUrl: true,
    url: "https://jennayey.itch.io/somber",
    linkText: "Play",
    isDeveloper: true,
    isDesigner: true,
  },
  {
    id: 3,
    title: "Noli Me Tangere",
    icon: "https://tailwindcss.com/_next/static/media/tailwindcss-mark.3c5441fc7a190fb1800d4a5c7f07ba4b1345a9c8.svg",
    inDevelopment: false,
    hasUrl: true,
    url: "https://jennayey.itch.io/nolimetangere",
    linkText: "Play",
    isDeveloper: false,
    isDesigner: true,
  },
];
